2022-11-19 16:40:50.127523: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-19 16:40:50.422728: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-19 16:40:50.539758: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-19 16:40:51.916862: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/apps/cuda/11.3.1/lib64
2022-11-19 16:40:51.917207: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/apps/cuda/11.3.1/lib64
2022-11-19 16:40:51.917217: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.2.3...
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
Traceback (most recent call last):
  File "/home/dje4001/post_dlc/dlc_process.py", line 7, in <module>
    import deeplabcut
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/deeplabcut/__init__.py", line 47, in <module>
    from deeplabcut.generate_training_dataset import (
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/deeplabcut/generate_training_dataset/__init__.py", line 12, in <module>
    from deeplabcut.generate_training_dataset.trainingsetmanipulation import *
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/deeplabcut/generate_training_dataset/trainingsetmanipulation.py", line 24, in <module>
    from deeplabcut.pose_estimation_tensorflow import training
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/__init__.py", line 12, in <module>
    from deeplabcut.pose_estimation_tensorflow.datasets import *
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/__init__.py", line 14, in <module>
    from .pose_tensorpack import TensorpackPoseDataset
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/datasets/pose_tensorpack.py", line 44, in <module>
    from tensorpack.dataflow.parallel import MultiProcessRunnerZMQ, MultiProcessRunner
  File "/home/dje4001/.local/lib/python3.8/site-packages/tensorpack/__init__.py", line 8, in <module>
    from tensorpack.dataflow import *
  File "/home/dje4001/.local/lib/python3.8/site-packages/tensorpack/dataflow/__init__.py", line 50, in <module>
    _global_import(module_name)
  File "/home/dje4001/.local/lib/python3.8/site-packages/tensorpack/dataflow/__init__.py", line 30, in _global_import
    p = __import__(name, globals(), locals(), level=1)
  File "/home/dje4001/.local/lib/python3.8/site-packages/tensorpack/dataflow/parallel.py", line 15, in <module>
    import zmq
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/zmq/__init__.py", line 103, in <module>
    from zmq import backend
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/zmq/backend/__init__.py", line 31, in <module>
    raise original_error from None
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/zmq/backend/__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/zmq/backend/select.py", line 31, in select_backend
    mod = import_module(name)
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/dje4001/.conda/envs/DEEPLABCUT_GUI/lib/python3.8/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)
